# This is the makefile for common assignment 4.
# Date: 21/03/2023
# By:	Bhuvneet Thakur, Maisa Wolff Resplande


# dependencies:	

./obj/common.o: ./src/common.c ../common/inc/common.h
		cc -c ./src/common.c -o ./obj/common.o

clean: 
	rm ./obj/*
