# This is the common makefile for CHAT-SYSTEM assignment 4.
# Date: 21/03/2023
# By:	Bhuvneet Thakur, Maisa Wolff Resplande

	
# other targets:

all: 
	(cd common; make -f makefile)
	(cd chat-client; make -f makefile)
	(cd chat-server; make -f makefile)
	
	
clean:
	(cd common; make -f makefile clean)
	(cd chat-client; make -f makefile clean)
	(cd chat-server; make -f makefile clean)
	
